### ISSUE TITLE
Maak gebruik van selector grouping

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/look-and-feel-corporate-identity#15]
@saschavanvliet hee! Ik weet niet of je eerder al tegen mij had gezegd of we gebruik konden maken van shorthand, maar ik had voor deze code nog een toevoeging.

https://github.com/SamaraFellaDina/look-and-feel-corporate-identity/blob/ab25d5171e78deb10ab79357954f5f3d126f88bd/styles/styles.css#L78C1-L102C49

Je kan in dit geval beter gebruik maken van selector grouping. Hij zou zo eigenlijk beter zo kunnen:

```css
.house1, .house2, .house3, .house4 {
    position: absolute;
    top: 12em;
    left: 25em;
    background-color: var(--grayscale-color-2);
    }

```
